CREATE DATABASE api;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
id serial NOT NULL PRIMARY KEY,
name text NOT NULL,
nick text NOT NULL,
password text NOT NULL,
email text UNIQUE NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
deleted_at TIMESTAMP WITH TIME ZONE
);

SELECT * FROM users;